version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Mapea el puerto 80 del contenedor al 8080 del host
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al 3000 del host

      